#!/usr/bin/env python
"""
Phase 9 Task 4: Bootstrap confidence intervals for structural distance matrix.

Resamples images (with replacement) within each architecture, recomputes the
mean drift profile → structural features → pairwise distance matrix, and
extracts 95% CI for each pairwise distance.

Uses per-image drift data from phase1 (SD 1.5), SDXL, DiT, SD 3.5, and
DiT-S/2 controlled experiment. FLUX has no per-image data → uses parametric
bootstrap from aggregated mean±std (less ideal, flagged).

Usage:
    python scripts/phase9_task4_bootstrap.py

Output: outputs/phase9_task4/
"""

import json
import sys
from pathlib import Path

import numpy as np

PROJECT_ROOT = Path(__file__).resolve().parent.parent
OUT_DIR = PROJECT_ROOT / "outputs" / "phase9_task4"
OUT_DIR.mkdir(parents=True, exist_ok=True)
N_BOOTSTRAP = 10000


# ---------------------------------------------------------------------------
# Structural features
# ---------------------------------------------------------------------------

def extract_structural_features(drift: np.ndarray) -> np.ndarray:
    L = len(drift)
    d = np.maximum(drift, 0.0)
    d_max = d.max()
    if d_max < 1e-12:
        return np.array([0.5, 0.0, 0.0, 0.0])
    peak_pos = float(np.argmax(d)) / max(L - 1, 1)
    n_peaks = float(np.sum(d > 0.7 * d_max))
    d_sorted = np.sort(d)
    n = len(d_sorted)
    index = np.arange(1, n + 1)
    gini = (2.0 * np.sum(index * d_sorted)) / (n * np.sum(d_sorted) + 1e-12) - (n + 1) / n
    spread = float(np.std(d) / (np.mean(d) + 1e-12))
    return np.array([peak_pos, n_peaks, gini, spread])


def structural_distance(d1: np.ndarray, d2: np.ndarray) -> float:
    return float(np.linalg.norm(extract_structural_features(d1) - extract_structural_features(d2)))


# ---------------------------------------------------------------------------
# Data loaders: return (layer_names, per_image_matrix: [n_layers, n_images])
# ---------------------------------------------------------------------------

def load_per_image_sd15():
    """SD 1.5 per-image drift. Generated by phase9_task4_sd15_perimage.py.
    Format: {layer_name: {image_name: drift_value}} (19 images, 38 layers)."""
    p = PROJECT_ROOT / "outputs" / "phase9_task4" / "sd15_per_image_drift.json"
    if not p.exists():
        print("  SD 1.5: per-image data not found — run phase9_task4_sd15_perimage.py first")
        return None, None, None
    with open(p) as f:
        data = json.load(f)
    per_img = data["per_image"]
    # Format: {layer_name: {image_name: drift_value}}
    layer_names = sorted(per_img.keys())
    first_layer = per_img[layer_names[0]]
    img_names = sorted(first_layer.keys())
    mat = np.array([[per_img[l][img] for img in img_names] for l in layer_names])
    return layer_names, mat, img_names


def load_per_image_sdxl():
    """SDXL per-image drift. 19 images, 28 layers."""
    with open(PROJECT_ROOT / "outputs" / "sdxl_phase1" / "layer_drift_summary.json") as f:
        data = json.load(f)
    per_img = data["per_image"]
    # Format: {layer_name: {image_name: value}}
    layer_names = sorted(per_img.keys())
    first_layer = per_img[layer_names[0]]
    img_names = sorted(first_layer.keys())
    mat = np.array([[per_img[l][img] for img in img_names] for l in layer_names])
    return layer_names, mat, img_names


def load_per_image_dit():
    """HunyuanDiT per-image drift. 19 images, 40 layers."""
    with open(PROJECT_ROOT / "outputs" / "dit_phase1" / "layer_drift_summary.json") as f:
        data = json.load(f)
    per_img = data["per_image"]
    layer_names = sorted(per_img.keys(), key=lambda x: int(x.split(".")[-1]))
    first_layer = per_img[layer_names[0]]
    img_names = sorted(first_layer.keys())
    mat = np.array([[per_img[l][img] for img in img_names] for l in layer_names])
    return layer_names, mat, img_names


def load_per_image_sd35():
    """SD 3.5 per-image drift. 19 images, 24 layers."""
    with open(PROJECT_ROOT / "outputs" / "sd35_phase1" / "layer_drift_summary.json") as f:
        data = json.load(f)
    per_img = data["per_image"]
    # Format: {image_name: {layer_name: value}}
    img_names = sorted(per_img.keys())
    first_img = per_img[img_names[0]]
    layer_names = sorted(first_img.keys(), key=lambda x: int(x.split("_")[-1]))
    mat = np.array([[per_img[img][l] for img in img_names] for l in layer_names])
    return layer_names, mat, img_names


def load_per_image_dit_controlled(variant="eps"):
    """DiT-S/2 controlled per-image drift. 19 images, 12 layers."""
    with open(PROJECT_ROOT / "outputs" / "train_controlled" / "diagnostics" / f"{variant}_drift.json") as f:
        data = json.load(f)
    per_img = data["per_image_drift"]
    # Format: {layer_name: [values_for_each_image]}
    layer_names = sorted(per_img.keys(), key=lambda x: int(x.split(".")[-1]))
    n_imgs = len(per_img[layer_names[0]])
    mat = np.array([per_img[l] for l in layer_names])
    img_names = [f"img_{i}" for i in range(n_imgs)]
    return layer_names, mat, img_names


def load_flux_aggregated():
    """FLUX has no per-image data; return aggregated mean drift (57 layers)."""
    with open(PROJECT_ROOT / "outputs" / "phase6_unified" / "results.json") as f:
        data = json.load(f)
    flux = data["architectures"]["FLUX (Transformer, Flow Match)"]
    layers = flux["layers"]
    drift_vec = np.array([l["drift"] for l in layers])
    return [l["name"] for l in layers], drift_vec


# ---------------------------------------------------------------------------
# Bootstrap
# ---------------------------------------------------------------------------

def bootstrap_distances(arch_data, arch_names, n_bootstrap=N_BOOTSTRAP):
    """
    arch_data: list of (name, per_image_matrix, img_names)
               per_image_matrix shape: [n_layers, n_images]
               For FLUX: per_image_matrix is 1D mean vector (treated as fixed).

    Returns: dict mapping pair -> {mean, ci_lower, ci_upper, std}
    """
    n_archs = len(arch_data)
    n_imgs_per_arch = []
    for nm, mat, imgs in arch_data:
        if mat.ndim == 2:
            n_imgs_per_arch.append(mat.shape[1])
        else:
            n_imgs_per_arch.append(0)  # Fixed aggregated

    # Storage for bootstrap distances
    pair_keys = []
    for i in range(n_archs):
        for j in range(i + 1, n_archs):
            pair_keys.append((i, j, f"{arch_data[i][0]} vs {arch_data[j][0]}"))

    boot_dists = {pk[2]: [] for pk in pair_keys}

    rng = np.random.RandomState(42)

    for _ in range(n_bootstrap):
        # Resample each architecture
        boot_profiles = []
        for a_idx, (nm, mat, imgs) in enumerate(arch_data):
            if mat.ndim == 2:
                n_imgs = mat.shape[1]
                idx = rng.randint(0, n_imgs, size=n_imgs)
                profile = mat[:, idx].mean(axis=1)
            else:
                # Fixed aggregated profile (FLUX) - no resampling
                profile = mat
            boot_profiles.append(profile)

        # Compute pairwise distances
        for i, j, key in pair_keys:
            d = structural_distance(boot_profiles[i], boot_profiles[j])
            boot_dists[key].append(d)

    # Compute CI
    results = {}
    for key, dists in boot_dists.items():
        dists = np.array(dists)
        results[key] = {
            "mean": float(np.mean(dists)),
            "std": float(np.std(dists)),
            "ci_95_lower": float(np.percentile(dists, 2.5)),
            "ci_95_upper": float(np.percentile(dists, 97.5)),
            "ci_99_lower": float(np.percentile(dists, 0.5)),
            "ci_99_upper": float(np.percentile(dists, 99.5)),
        }
    return results


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    print("Loading per-image drift data...")

    arch_data = []

    # SD 1.5
    layers_sd15, mat_sd15, imgs_sd15 = load_per_image_sd15()
    if mat_sd15 is not None:
        arch_data.append(("SD1.5", mat_sd15, imgs_sd15))
        print(f"  SD 1.5: {mat_sd15.shape[0]} layers, {mat_sd15.shape[1]} images")
    else:
        print("  SD 1.5: WARNING — no per-image data, SKIPPED")

    # SDXL
    layers_sdxl, mat_sdxl, imgs_sdxl = load_per_image_sdxl()
    arch_data.append(("SDXL", mat_sdxl, imgs_sdxl))
    print(f"  SDXL: {mat_sdxl.shape[0]} layers, {mat_sdxl.shape[1]} images")

    # HunyuanDiT
    layers_dit, mat_dit, imgs_dit = load_per_image_dit()
    arch_data.append(("DiT", mat_dit, imgs_dit))
    print(f"  HunyuanDiT: {mat_dit.shape[0]} layers, {mat_dit.shape[1]} images")

    # SD 3.5
    layers_sd35, mat_sd35, imgs_sd35 = load_per_image_sd35()
    arch_data.append(("SD3.5", mat_sd35, imgs_sd35))
    print(f"  SD 3.5: {mat_sd35.shape[0]} layers, {mat_sd35.shape[1]} images")

    # FLUX (aggregated only)
    layers_flux, drift_flux = load_flux_aggregated()
    arch_data.append(("FLUX", drift_flux, []))
    print(f"  FLUX: {len(drift_flux)} layers (aggregated, no per-image bootstrap)")

    # DiT-S/2 eps and flow
    layers_ds_eps, mat_ds_eps, imgs_ds_eps = load_per_image_dit_controlled("epsilon")
    arch_data.append(("DiT-S/2_eps", mat_ds_eps, imgs_ds_eps))
    print(f"  DiT-S/2 eps: {mat_ds_eps.shape[0]} layers, {mat_ds_eps.shape[1]} images")

    layers_ds_flow, mat_ds_flow, imgs_ds_flow = load_per_image_dit_controlled("flow")
    arch_data.append(("DiT-S/2_flow", mat_ds_flow, imgs_ds_flow))
    print(f"  DiT-S/2 flow: {mat_ds_flow.shape[0]} layers, {mat_ds_flow.shape[1]} images")

    # ---- Bootstrap ----
    print(f"\nRunning {N_BOOTSTRAP} bootstrap iterations...")
    boot_results = bootstrap_distances(arch_data, [a[0] for a in arch_data], N_BOOTSTRAP)

    # ---- Summarize ----
    print(f"\n{'='*70}")
    print(f"{'Pair':<30} {'Mean d':>8} {'95% CI':>20} {'Std':>8}")
    print("-" * 70)

    for key, vals in sorted(boot_results.items()):
        print(f"{key:<30} {vals['mean']:>8.4f} [{vals['ci_95_lower']:.4f}, {vals['ci_95_upper']:.4f}]  {vals['std']:>8.4f}")

    # Highlight DiT-S/2 pair
    dit_key = "DiT-S/2_eps vs DiT-S/2_flow"
    if dit_key in boot_results:
        d_dit = boot_results[dit_key]
        # Find min cross-architecture (exclude DiT-S/2 pairs)
        cross_pairs = {k: v for k, v in boot_results.items()
                       if "DiT-S/2" not in k}
        min_cross = min(cross_pairs.values(), key=lambda x: x["mean"])
        print(f"\n{'='*70}")
        print(f"DiT-S/2 eps-flow distance: {d_dit['mean']:.4f} [{d_dit['ci_95_lower']:.4f}, {d_dit['ci_95_upper']:.4f}]")
        print(f"Min cross-arch distance:    {min_cross['mean']:.4f} [{min_cross['ci_95_lower']:.4f}, {min_cross['ci_95_upper']:.4f}]")
        print(f"  -> {min(cross_pairs, key=lambda x: cross_pairs[x]['mean'])}")

        # Conservative test: compare upper CI of DiT against lower CI of min cross
        if d_dit["ci_95_upper"] < min_cross["ci_95_lower"]:
            verdict = "STRONG: DiT 95% CI upper bound < min cross-arch 95% CI lower bound (non-overlapping CIs)"
        elif d_dit["ci_99_upper"] < min_cross["ci_99_lower"]:
            verdict = "MODERATE: Non-overlapping at 99% CI"
        elif d_dit["mean"] + 2 * d_dit["std"] < min_cross["mean"] - 2 * min_cross["std"]:
            verdict = "ADEQUATE: >2σ separation between distributions"
        else:
            verdict = "WEAK: overlapping distributions — larger sample needed"
        print(f"\nVerdict: {verdict}")

    # Save
    output = {
        "n_bootstrap": N_BOOTSTRAP,
        "architectures": [a[0] for a in arch_data],
        "n_images_per_arch": {a[0]: (a[1].shape[1] if a[1].ndim == 2 else 0) for a in arch_data},
        "bootstrap_results": boot_results,
        "verdict": verdict if 'verdict' in dir() else "N/A",
        "note_sd15": "No per-image data — excluded from bootstrap" if mat_sd15 is None else "OK",
        "note_flux": "Aggregated only — not bootstrapped, treated as fixed",
    }

    out_path = OUT_DIR / "bootstrap_ci.json"
    with open(out_path, "w") as f:
        json.dump(output, f, indent=2)
    print(f"\nSaved: {out_path}")


if __name__ == "__main__":
    main()
